from __future__ import annotations

import json
from pathlib import Path


def export_promptfoo_yaml(input_path: Path, output_path: Path | None = None) -> str:
    """Convert PromptGuard eval JSONL into a minimal promptfoo YAML skeleton."""
    cases: list[dict] = []
    for line in input_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        cases.append(json.loads(line))

    # Manual YAML (stdlib only) — keep simple and valid for promptfoo init.
    lines = [
        "# Generated by promptguard export-promptfoo",
        "# Skeleton only: wire providers and grade with your own asserts.",
        "# Expected PromptGuard rule ids are recorded in description metadata.",
        "",
        "description: PromptGuard eval export",
        "prompts:",
        "  - \"{{prompt}}\"",
        "providers:",
        "  - echo",
        "tests:",
    ]
    if not cases:
        lines.append("  []")
    for case in cases:
        cid = str(case.get("id", "case"))
        prompt = str(case.get("prompt", "")).replace("\\", "\\\\").replace('"', '\\"')
        expected = case.get("expected") or []
        if not isinstance(expected, list):
            expected = [expected]
        expected_s = ", ".join(str(x) for x in expected) if expected else "(none)"
        kind = case.get("kind", "")
        rationale = str(case.get("rationale", "")).replace("\n", " ")
        lines.append(f"  - description: \"{cid} [{kind}] expect {expected_s}\"")
        lines.append("    vars:")
        lines.append(f"      prompt: \"{prompt}\"")
        lines.append("    assert:")
        lines.append(f"      # PromptGuard static expect: {expected_s}")
        if rationale:
            lines.append(f"      # rationale: {rationale}")
        lines.append("      - type: javascript")
        lines.append("        value: \"true  // replace with model/behavior asserts\"")

    yaml_text = "\n".join(lines) + "\n"
    if output_path is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(yaml_text, encoding="utf-8")
    return yaml_text
